#!/usr/bin/env node


 // This is getting the db connection from sequalize
const { db } = require('../models');



// async call (since were awaiting ap promise)
(async () => {
  await db.sync({ force: true });
  // IMPORTANT –> close the connection
  db.close();
})();
